### ISSUE TITLE
Updating to 94 using the 

### ISSUE THREAD

**Issue by pierluigizagaria** [cyfinoid/hbctool#11]
I'm trying to update the tool for version 94 however I'm getting this error when running the disasm command. I've followed the 
[ADD_NEW_VERSION](https://github.com/cyfinoid/hbctool/blob/main/ADD_NEW_VERSION.md) guide. This is the stack trace.
```
PS C:\Users\Pierluigi\Downloads\Lovebox_7.3.2> hbctool disasm .\assets\index.android.bundle .\assets\hasm\
[*] Hermes Bytecode [ Source Hash: b8ceb613053a8e2c27fdd5e63578f927ce97b9d3, HBC Version: 94 ]
Traceback (most recent call last):
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\Scripts\hbctool.exe\__main__.py", line 7, in <module>
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\hbctool\__init__.py", line 61, in main
    disasm(args['<HBC_FILE>'], args['<HASM_PATH>'])
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\hbctool\__init__.py", line 41, in disasm
    hasm.dump(hbco, hasmpath)
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\hbctool\hasm.py", line 67, in dump
    write_func(f, hbc.getFunction(i), i, hbc)
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\hbctool\hbc\hbc94\__init__.py", line 60, in getFunction
    insts = disassemble(bc)
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\hbctool\hbc\hbc94\translator.py", line 43, in disassemble
    val = conv_to(bc[i:i+size])
  File "C:\Users\Pierluigi\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\hbctool\util.py", line 297, in to_uint8
    return buf[0]
IndexError: list index out of range
```

Any suggestion to fix this problem? Thank you

**Comment by weilanxiao** [comment]
I encountered this issue while supporting version 96. #12
