### ISSUE TITLE
ERROR: unpack requires a buffer of 2 bytes (HBC Version: 89)

### ISSUE THREAD

**Issue by gonzalo-hvega** [cyfinoid/hbctool#8]
Hi, I am trying to to reverse an APK which contains HBC Version 89, however I get the following error while it tries to unpack the instruction.hasm:

Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "D:\Programs\Python-3.6.8\Scripts\hbctool.exe\__main__.py", line 7, in <module>
  File "d:\programs\python-3.6.8\lib\site-packages\hbctool\__init__.py", line 61, in main
    disasm(args['<HBC_FILE>'], args['<HASM_PATH>'])
  File "d:\programs\python-3.6.8\lib\site-packages\hbctool\__init__.py", line 41, in disasm
    hasm.dump(hbco, hasmpath)
  File "d:\programs\python-3.6.8\lib\site-packages\hbctool\hasm.py", line 67, in dump
    write_func(f, hbc.getFunction(i), i, hbc)
  File "d:\programs\python-3.6.8\lib\site-packages\hbctool\hbc\hbc89\__init__.py", line 59, in getFunction
    insts = disassemble(bc)
  File "d:\programs\python-3.6.8\lib\site-packages\hbctool\hbc\hbc89\translator.py", line 43, in disassemble
    val = conv_to(bc[i:i+size])
  File "d:\programs\python-3.6.8\lib\site-packages\hbctool\util.py", line 300, in to_uint16
    return unpack("<H", bytes(buf[:2]))[0]
struct.error: unpack requires a buffer of 2 bytes

**Comment by hab12335** [comment]
Same problem here, altough in my apk it's in "to_uint8"

**Comment by Happiness777** [comment]
> Hi, I am trying to to reverse an APK which contains HBC Version 89, however I get the following error while it tries to unpack the instruction.hasm:
> 
> Traceback (most recent call last): File "runpy.py", line 193, in _run_module_as_main File "runpy.py", line 85, in _run_code File "D:\Programs\Python-3.6.8\Scripts\hbctool.exe__main__.py", line 7, in File "d:\programs\python-3.6.8\lib\site-packages\hbctool__init__.py", line 61, in main disasm(args['<HBC_FILE>'], args['<HASM_PATH>']) File "d:\programs\python-3.6.8\lib\site-packages\hbctool__init__.py", line 41, in disasm hasm.dump(hbco, hasmpath) File "d:\programs\python-3.6.8\lib\site-packages\hbctool\hasm.py", line 67, in dump write_func(f, hbc.getFunction(i), i, hbc) File "d:\programs\python-3.6.8\lib\site-packages\hbctool\hbc\hbc89__init__.py", line 59, in getFunction insts = disassemble(bc) File "d:\programs\python-3.6.8\lib\site-packages\hbctool\hbc\hbc89\translator.py", line 43, in disassemble val = conv_to(bc[i:i+size]) File "d:\programs\python-3.6.8\lib\site-packages\hbctool\util.py", line 300, in to_uint16 return unpack("<H", bytes(buf[:2]))[0] struct.error: unpack requires a buffer of 2 bytes

Having the same issue here.
Did anyone find a fix for it?

**Comment by pkarnstein-SI** [comment]
I am also getting this problem, after following the instructions to upgrade for HASM 96
